"""
      Represents an enum type item
      """
      type EnumTypeItem {
        """
        The underlying value of the item.
        """
        value: String!
      
        """
        The display text of the value in English.
        """
        value: String!
      
        """
        The documentation associated with this item.
        """
        documentation: String
      
        """
        If populated, this value explains why the value was deprecated and/or which item to use instead.
        """
        deprecated: String
      
        """
        A symbol associated with the item.
        """
        symbol: String
      }
      
      enum Color {
        RED
        GREEN
      },enum Size {
        REGULAR
        LARGE
        XLARGE
      },enum Direction {
        UP
        DOWN
      }
      
      """
      Custom data that is attached to each color enum item.
      """
      type Color_Data {
        hexCode: String!
      
        isWarningColor: Boolean
      }
      
      ,"""
      A bed
      """
      type Bed {
        make: String!
      
        thickness: Float
      
        pillow: Pillow
      
        """
        A value from the **direction** enum of the **alt** type system defined by **https://jsonotron.org**.
        """
        direction: JSON
      }
      
      ,"""
      A pillow
      """
      type Pillow {
        make: String!
      
        color: String
      }
      
      ,"""
      The drawer type.
      """
      type Drawer {
        instructions: JSON
      
        compact: Boolean
      
        fabrics: String
      
        enumNumbers: Float
      
        enumBoolean: Boolean
      
        enumObjects: JSON
      
        contents: [String]
      
        complexContents: [String]
      
        """
        The age in years.
        """
        age: Int
      }
      
      ,"""
      A table
      """
      type Table {
        height: Float
      }