export const currencyCode = {
  name: 'currencyCode',
  title: 'Currency Code',
  paragraphs: [
    'A currency designator from ISO 4217.  The data is taken from https://en.wikipedia.org/wiki/ISO_4217.'
  ],
  items: [
    { value: 'aed', symbol: 'د.إ', text: 'United Arab Emirates Dirham' },
    { value: 'afn', symbol: 'AFN', text: 'Afghan Afghani' },
    { value: 'all', symbol: 'ALL', text: 'Albanian Lek' },
    { value: 'amd', symbol: 'AMD', text: 'Armenian Dram' },
    { value: 'ang', symbol: 'ANG', text: 'Netherlands Antillean Guilder' },
    { value: 'aoa', symbol: 'AOA', text: 'Angolan Kwanza' },
    { value: 'ars', symbol: 'ARS', text: 'Argentine Peso' },
    { value: 'aud', symbol: '$', text: 'Australian Dollar' },
    { value: 'awg', symbol: 'AWG', text: 'Aruban Florin' },
    { value: 'azn', symbol: 'AZN', text: 'Azerbaijani Manat' },
    { value: 'bam', symbol: 'BAM', text: 'Bosnia and Herzegovina Convertible Mark' },
    { value: 'bbd', symbol: 'BBD', text: 'Barbados Dollar' },
    { value: 'bdt', symbol: '৳', text: 'Bangladeshi Taka' },
    { value: 'bgn', symbol: 'лв', text: 'Bulgarian Lev' },
    { value: 'bhd', symbol: 'BHD', text: 'Bahraini Dinar' },
    { value: 'bif', symbol: 'BIF', text: 'Burundian Franc' },
    { value: 'bmd', symbol: 'BMD', text: 'Bermudian Dollar' },
    { value: 'bnd', symbol: 'BND', text: 'Brunei Dollar' },
    { value: 'bob', symbol: 'BOB', text: 'Boliviano' },
    { value: 'bov', symbol: 'BOV', text: 'Bolivian Mvdol (funds code)' },
    { value: 'brl', symbol: 'R$', text: 'Brazilian Real' },
    { value: 'bsd', symbol: 'BSD', text: 'Bahamian Dollar' },
    { value: 'btc', symbol: '₿', text: 'Bitcoin' },
    { value: 'btn', symbol: 'BTN', text: 'Bhutanese Ngultrum' },
    { value: 'bwp', symbol: 'BWP', text: 'Botswana Pula' },
    { value: 'byn', symbol: 'BYN', text: 'Belarusian Ruble' },
    { value: 'bzd', symbol: 'BZD', text: 'Belize Dollar' },
    { value: 'cad', symbol: '$', text: 'Canadian Dollar' },
    { value: 'cdf', symbol: 'CDF', text: 'Congolese Franc' },
    { value: 'che', symbol: '€', text: 'WIR Euro' },
    { value: 'chf', symbol: 'CHF', text: 'Swiss Franc' },
    { value: 'chw', symbol: 'CHW', text: 'WIR Franc' },
    { value: 'clf', symbol: 'CLF', text: 'Unidad de Fomento (funds code)' },
    { value: 'clp', symbol: '$', text: 'Chilean Peso' },
    { value: 'cny', symbol: '¥', text: 'Renminbi (Chinese) Yuan' },
    { value: 'cop', symbol: '$', text: 'Colombian Peso' },
    { value: 'cou', symbol: 'COU', text: 'Unidad de Valor Real (UVR)' },
    { value: 'crc', symbol: 'CRC', text: 'Costa Rican Colon' },
    { value: 'cuc', symbol: 'CUC', text: 'Cuban convertible Peso' },
    { value: 'cup', symbol: 'CUP', text: 'Cuban Peso' },
    { value: 'cve', symbol: 'CVE', text: 'Cape Verdean Escudo' },
    { value: 'czk', symbol: 'Kč', text: 'Czech Koruna' },
    { value: 'djf', symbol: 'DJF', text: 'Djiboutian Franc' },
    { value: 'dkk', symbol: 'kr', text: 'Danish Krone' },
    { value: 'dop', symbol: 'DOP', text: 'Dominican Peso' },
    { value: 'dzd', symbol: 'DZD', text: 'Algerian Dinar' },
    { value: 'egp', symbol: 'EGP', text: 'Egyptian Pound' },
    { value: 'ern', symbol: 'ERN', text: 'Eritrean Nakfa' },
    { value: 'etb', symbol: 'ETB', text: 'Ethiopian Birr' },
    { value: 'eth', symbol: 'Ξ', text: 'Etherium' },
    { value: 'eur', symbol: '€', text: 'Euro' },
    { value: 'fjd', symbol: 'FJD', text: 'Fiji Dollar' },
    { value: 'fkp', symbol: 'FKP', text: 'Falkland Islands Pound' },
    { value: 'gbp', symbol: '£', text: 'Pound Sterling' },
    { value: 'gel', symbol: '₾', text: 'Georgian Lari' },
    { value: 'ghs', symbol: 'GHS', text: 'Ghanaian Cedi' },
    { value: 'gip', symbol: 'GIP', text: 'Gibraltar Pound' },
    { value: 'gmd', symbol: 'GMD', text: 'Gambian Dalasi' },
    { value: 'gnf', symbol: 'GNF', text: 'Guinean Franc' },
    { value: 'gtq', symbol: 'GTQ', text: 'Guatemalan Quetzal' },
    { value: 'gyd', symbol: 'GYD', text: 'Guyanese Dollar' },
    { value: 'hkd', symbol: '$', text: 'Hong Kong Dollar' },
    { value: 'hnl', symbol: 'HNL', text: 'Honduran Lempira' },
    { value: 'hrk', symbol: 'kn', text: 'Croatian Kuna' },
    { value: 'htg', symbol: 'HTG', text: 'Haitian Gourde' },
    { value: 'huf', symbol: 'ft', text: 'Hungarian Forint' },
    { value: 'idr', symbol: 'Rp', text: 'Indonesian Rupiah' },
    { value: 'ils', symbol: '₪', text: 'Israeli New Shekel' },
    { value: 'inr', symbol: '₹', text: 'Indian Rupee' },
    { value: 'iqd', symbol: 'IQD', text: 'Iraqi Dinar' },
    { value: 'irr', symbol: 'IRR', text: 'Iranian Rial' },
    { value: 'isk', symbol: 'ISK', text: 'Icelandic Króna' },
    { value: 'jmd', symbol: 'JMD', text: 'Jamaican Dollar' },
    { value: 'jod', symbol: 'JOD', text: 'Jordanian Dinar' },
    { value: 'jpy', symbol: '¥', text: 'Japanese Yen' },
    { value: 'kes', symbol: 'Ksh', text: 'Kenyan Shilling' },
    { value: 'kgs', symbol: 'KGS', text: 'Kyrgyzstani Som' },
    { value: 'khr', symbol: 'KHR', text: 'Cambodian Riel' },
    { value: 'kmf', symbol: 'KMF', text: 'Comoro Franc' },
    { value: 'kpw', symbol: '$KPW', text: 'North Korean Won' },
    { value: 'krw', symbol: '₩', text: 'South Korean Won' },
    { value: 'kwd', symbol: 'KWD', text: 'Kuwaiti Dinar' },
    { value: 'kyd', symbol: 'KYD', text: 'Cayman Islands Dollar' },
    { value: 'kzt', symbol: 'KZT', text: 'Kazakhstani Tenge' },
    { value: 'lak', symbol: 'LAK', text: 'Lao Kip' },
    { value: 'lbp', symbol: 'LBP', text: 'Lebanese Pound' },
    { value: 'lkr', symbol: 'Rs', text: 'Sri Lankan Rupee' },
    { value: 'lrd', symbol: 'LRD', text: 'Liberian Dollar' },
    { value: 'lsl', symbol: 'LDL', text: 'Lesotho Loti' },
    { value: 'ltc', symbol: 'Ł', text: 'Litecoin' },
    { value: 'lyd', symbol: 'LYD', text: 'Libyan Dinar' },
    { value: 'mad', symbol: '.د.م', text: 'Moroccan Dirham' },
    { value: 'mdl', symbol: 'MDL', text: 'Moldovan Leu' },
    { value: 'mga', symbol: 'MGA', text: 'Malagasy Ariary' },
    { value: 'mkd', symbol: 'MKD', text: 'Macedonian Denar' },
    { value: 'mmk', symbol: 'MMK', text: 'Myanmar Kyat' },
    { value: 'mnt', symbol: 'MNT', text: 'Mongolian Tögrög' },
    { value: 'mop', symbol: 'MOP', text: 'Macanese Pataca' },
    { value: 'mru', symbol: 'MRU', text: 'Mauritanian Ouguiya' },
    { value: 'mur', symbol: 'MUR', text: 'Mauritian Rupee' },
    { value: 'mvr', symbol: 'MVR', text: 'Maldivian Rufiyaa' },
    { value: 'mwk', symbol: 'MWK', text: 'Malawian Kwacha' },
    { value: 'mxn', symbol: '$', text: 'Mexican Peso' },
    { value: 'mxv', symbol: 'MXV', text: 'Mexican Unidad de Inversion (UDI)' },
    { value: 'myr', symbol: 'RM', text: 'Malaysian Ringgit' },
    { value: 'mzn', symbol: 'MZN', text: 'Mozambican Metical' },
    { value: 'nad', symbol: 'NAD', text: 'Namibian Dollar' },
    { value: 'ngn', symbol: '₦', text: 'Nigerian Naira' },
    { value: 'nio', symbol: 'NIO', text: 'Nicaraguan Córdoba' },
    { value: 'nok', symbol: 'kr', text: 'Norwegian Krone' },
    { value: 'npr', symbol: 'NPR', text: 'Nepalese Rupee' },
    { value: 'nzd', symbol: '$', text: 'New Zealand Dollar' },
    { value: 'omr', symbol: 'OMR', text: 'Omani Rial' },
    { value: 'pab', symbol: 'PAB', text: 'Panamanian Balboa' },
    { value: 'pen', symbol: 'S/.', text: 'Peruvian Sol' },
    { value: 'pgk', symbol: 'PGK', text: 'Papua New Guinean Kina' },
    { value: 'php', symbol: '₱', text: 'Philippine Peso' },
    { value: 'pkr', symbol: 'Rs', text: 'Pakistani Rupee' },
    { value: 'pln', symbol: 'zł', text: 'Polish Złoty' },
    { value: 'pyg', symbol: 'PYG', text: 'Paraguayan Guaraní' },
    { value: 'qar', symbol: 'QAR', text: 'Qatari Riyal' },
    { value: 'ron', symbol: 'lei', text: 'Romanian Leu' },
    { value: 'rsd', symbol: 'RSD', text: 'Serbian Dinar' },
    { value: 'rub', symbol: '₽', text: 'Russian Ruble' },
    { value: 'rwf', symbol: 'RWF', text: 'Rwandan Franc' },
    { value: 'sar', symbol: 'SAR', text: 'Saudi Riyal' },
    { value: 'sbd', symbol: 'SBD', text: 'Solomon Islands Dollar' },
    { value: 'scr', symbol: 'SCR', text: 'Seychelles Rupee' },
    { value: 'sdg', symbol: 'SDG', text: 'Sudanese Pound' },
    { value: 'sek', symbol: 'kr', text: 'Swedish Krona/Kronor' },
    { value: 'sgd', symbol: '$', text: 'Singapore Dollar' },
    { value: 'shp', symbol: 'SHP', text: 'Saint Helena Pound' },
    { value: 'sll', symbol: 'SLL', text: 'Sierra Leonean Leone' },
    { value: 'sos', symbol: 'SOS', text: 'Somali Shilling' },
    { value: 'srd', symbol: 'SRD', text: 'Surinamese Dollar' },
    { value: 'ssp', symbol: 'SSP', text: 'South Sudanese Pound' },
    { value: 'stn', symbol: 'STN', text: 'São Tomé and Príncipe Dobra' },
    { value: 'svc', symbol: 'SVC', text: 'Salvadoran Colón' },
    { value: 'syp', symbol: 'SYP', text: 'Syrian Pound' },
    { value: 'szl', symbol: 'SZL', text: 'Swazi Lilangeni' },
    { value: 'thb', symbol: '฿', text: 'Thai Baht' },
    { value: 'tjs', symbol: 'TJS', text: 'Tajikistani Somoni' },
    { value: 'tmt', symbol: 'TMT', text: 'Turkmenistan Manat' },
    { value: 'tnd', symbol: 'TND', text: 'Tunisian Dinar' },
    { value: 'top', symbol: 'TOP', text: 'Tongan Paʻanga' },
    { value: 'try', symbol: '₺', text: 'Turkish Lira' },
    { value: 'ttd', symbol: 'TTD', text: 'Trinidad and Tobago Dollar' },
    { value: 'twd', symbol: 'TWD', text: 'New Taiwan Dollar' },
    { value: 'tzs', symbol: 'TZS', text: 'Tanzanian Shilling' },
    { value: 'uah', symbol: '₴', text: 'Ukrainian Hryvnia' },
    { value: 'ugx', symbol: 'UGX', text: 'Ugandan Shilling' },
    { value: 'usd', symbol: '$', text: 'United States Dollar' },
    { value: 'usn', symbol: '$', text: 'United States Dollar (next day)' },
    { value: 'uyi', symbol: 'UYI', text: 'Uruguay Peso en Unidades Indexadas (URUIURUI)' },
    { value: 'uyu', symbol: 'UYU', text: 'Uruguayan Peso' },
    { value: 'uyw', symbol: 'UYW', text: 'Unidad Previsional' },
    { value: 'uzs', symbol: 'UZS', text: 'Uzbekistan Som' },
    { value: 'ves', symbol: 'VES', text: 'Venezuelan Bolívar Soberano' },
    { value: 'vnd', symbol: '₫', text: 'Vietnamese Dồng' },
    { value: 'vuv', symbol: 'VUV', text: 'Vanuatu Vatu' },
    { value: 'wst', symbol: 'WST', text: 'Samoan Tala' },
    { value: 'xaf', symbol: 'XAF', text: 'CFA franc BEAC' },
    { value: 'xag', symbol: 'XAG', text: 'Silver (one troy ounce)' },
    { value: 'xau', symbol: 'XAU', text: 'Gold (one troy ounce)' },
    { value: 'xba', symbol: 'XBA', text: 'European Composite Unit (EURCO)' },
    { value: 'xbb', symbol: 'XBB', text: 'European Monetary Unit (E.M.U.-6)' },
    { value: 'xbc', symbol: 'XBC', text: 'European Unit of Account 9 (E.U.A.-9)' },
    { value: 'xbd', symbol: 'XBD', text: 'European Unit of Account 17 (E.U.A.-17)' },
    { value: 'xcd', symbol: 'XCD', text: 'East Caribbean Dollar' },
    { value: 'xdr', symbol: 'XDR', text: 'Special Drawing Rights' },
    { value: 'xmr', symbol: 'ɱ', text: 'Monero' },
    { value: 'xof', symbol: 'XOF', text: 'CFA Franc BCEAO' },
    { value: 'xpd', symbol: 'XPD', text: 'Palladium (one troy ounce)' },
    { value: 'xpf', symbol: 'XPF', text: 'CFP Franc (franc Pacifique)' },
    { value: 'xpt', symbol: 'XPT', text: 'Platinum (one troy ounce)' },
    { value: 'xrp', symbol: 'XRP', text: 'Ripples' },
    { value: 'xsu', symbol: 'XSU', text: 'SUCRE' },
    { value: 'xts', symbol: 'XTS', text: 'Code Reserved for Testing' },
    { value: 'xua', symbol: 'XUA', text: 'ADB Unit of Account' },
    { value: 'xxx', symbol: 'XXX', text: 'No Currency' },
    { value: 'yer', symbol: 'YER', text: 'Yemeni Rial' },
    { value: 'zar', symbol: 'R', text: 'South African Rand' },
    { value: 'zmw', symbol: 'ZMW', text: 'Zambian Kwacha' },
    { value: 'zwl', symbol: 'ZWL', text: 'Zimbabwean Dollar' }
  ]
}
