name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
    - name: Setup Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Install deps
      run: npm ci
    - name: Build jsonotron-interfaces
      run: |
        cd workspaces/jsonotron-interfaces
        npm run build
    - name: Test jsonotron-js
      run: |
        cd workspaces/jsonotron-js
        npm test
        npm run build
    - name: Test jss
      run: |
        cd workspaces/jss
        npm test
        npm run generate-docs
    - name: Test jsonoserve
      run: |
        cd workspaces/jsonoserve
        npm test
        npm run build
    - name: Test jsonocli
      run: |
        cd workspaces/jsonocli
        npm run build
